wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1676006672
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      4: 3.9.12
      5: 0.12.16
      6: 4.17.0
      8:
      - 3
      - 5
anneal_lr:
  desc: null
  value: false
anneal_lr_steps:
  desc: null
  value: 100000
batchsize:
  desc: null
  value: -1
d_model:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.0
math_operator:
  desc: null
  value: +
max_context_len:
  desc: null
  value: 50
max_epochs:
  desc: null
  value: 2
max_lr:
  desc: null
  value: 0.001
max_steps:
  desc: null
  value: '100000'
momentum:
  desc: null
  value: '0.9'
n_heads:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 2
noise_factor:
  desc: null
  value: 0
operand_length:
  desc: null
  value: null
opt:
  desc: null
  value: adamw
random_seed:
  desc: null
  value: 0
train_data_pct:
  desc: null
  value: 40
warmup_steps:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 0.0
weight_decay_kind:
  desc: null
  value: to_zero
weight_noise:
  desc: null
  value: 0.0
